[package]
name = "SAMM"
type = "bin"
authors = ["@dry914"]
compiler_version = ">=0.35.0"

[dependencies]
string_search = { tag = "v0.2.0", git = "https://github.com/noir-lang/noir_string_search"  }
rsa = { tag = "v0.3.1", git = "https://github.com/noir-lang/noir_rsa", directory = "lib" }
zkemail = { tag = "v0.3.1", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }