[package]
name = "SAMM"
type = "bin"
authors = ["@dry914"]
compiler_version = ">=0.32.0"

[dependencies]
string_search = { tag = "v0.1", git = "https://github.com/noir-lang/noir_string_search"  }
noir_rsa = { tag = "v0.2", git = "https://github.com/noir-lang/noir_rsa" }